import type { RepoScan } from "../types/index.js";
import { code, list, pluralize } from "../utils/markdown.js";
import { moduleLabel } from "../utils/moduleLabel.js";
import { buildAreaFlows } from "../knowledge/areaFlows.js";
import { areaDocFileName } from "../utils/docPaths.js";
import { renderInstallCommand, renderRepoWikiCommands, renderRepoWikiFlags } from "./repoWikiCli.js";
import { summaryExcerpt } from "../utils/summaryExcerpt.js";
import { orderedAreas } from "../knowledge/areaOrdering.js";

const start = "<!-- REPOWIKI:START -->";
const end = "<!-- REPOWIKI:END -->";

export function generateAgentsSection(scan: RepoScan): string {
  const areas = orderedAreas(scan);
  return `${start}
# Agent Instructions

This section was generated by RepoWiki.

## Before Making Changes

Read:
- docs/repo-wiki/index.md
- docs/repo-wiki/architecture.md
- docs/repo-wiki/agent-context.md
- docs/repo-wiki/flows/index.md
- docs/repo-wiki/areas/index.md
- docs/repo-wiki/codex-review.md

## Project Structure

${list(scan.graph.modules.map((module) => `${code(module.rootPath)} - ${module.purpose ?? "Detected from file structure."}`))}

## Important Commands

${list([renderInstallCommand(scan), ...Object.entries(scan.project.scripts).map(([name, value]) => `${code(name)}: ${code(value)}`)])}

## RepoWiki Commands

${list(renderRepoWikiCommands(scan), "_No RepoWiki commands detected._")}

## RepoWiki Flags

${list(renderRepoWikiFlags(scan), "_No RepoWiki flags detected._")}

## Module-Specific Notes

${list(scan.graph.modules.map((module) => `${code(moduleLabel(module))}: ${pluralize(module.files.length, "file")} under ${code(module.rootPath)}`))}

## Module Areas

${list(areas.map((area) => `${code(area.name)}: ${pluralize(area.modules.length, "module")}${area.purpose ? ` - ${area.purpose}` : ""}`), "_No module areas detected._")}

## Area Summaries

${list(areas.map((area) => `[${area.name}](docs/repo-wiki/areas/${areaDocFileName(area.id)}) - ${summaryExcerpt(scan.summaries?.areas?.[area.id]?.content ?? area.purpose ?? "Connected implementation area.")}`), "_No area summaries available._")}

## Area Docs

Read ${code("docs/repo-wiki/areas/index.md")} for the area-level map.

${list(areas.map((area) => `[${area.name}](docs/repo-wiki/areas/${areaDocFileName(area.id)}) - ${pluralize(area.modules.length, "module")}`), "_No area docs generated._")}

## Area Flows

${list(buildAreaFlows(scan).slice(0, 5).map((flow) => `${code(flow.fromName)} -> ${code(flow.toName)} (${flow.count} imports)`), "_No area-to-area flows detected._")}

## Safety Rules

- Do not edit database migrations casually.
- Update tests when changing business logic.
- Update docs/repo-wiki when changing public APIs, auth, database models, or deployment config.
${end}`;
}

export function mergeAgentsMd(existing: string | undefined, section: string): string {
  if (!existing?.trim()) return `${section}\n`;
  const pattern = new RegExp(`${escapeRegExp(start)}[\\s\\S]*?${escapeRegExp(end)}`);
  if (pattern.test(existing)) return `${existing.replace(pattern, section).trimEnd()}\n`;
  return `${existing.trimEnd()}\n\n${section}\n`;
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
